### PR TITLE
Fixes #10 by using a single directory (in bower's cache directory) instead of individual tmp directories

### LINKED ISSUE #10: "Path must be a string. Received undefined" error during parallel downloads
When several packages are downloaded simultaneously from a private npm registry, it's possible to get a `Path must be a string. Received undefined` error message:

```
bower my-internal-module#0.1.1                 error Path must be a string. Received undefined

Stack trace:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:466:7)
    at ResolveCache._readPkgMeta (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\core\ResolveCache.js:337:25)
    at ResolveCache.store (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\core\ResolveCache.js:108:51)
    at C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\core\PackageRepository.js:190:35
    at _fulfilled (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:796:13)
    at C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:604:44
    at runSingle (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:137:13)

Console trace:
Error
    at StandardRenderer.error (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\renderers\StandardRenderer.js:81:37)
    at Logger.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\bin\bower.js:110:26)
    at emitOne (events.js:96:13)
    at Logger.emit (events.js:188:7)
    at Logger.emit (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\bower-logger\lib\Logger.js:29:39)
    at C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\commands\index.js:48:20
    at _rejected (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:844:24)
    at C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:870:30
    at Promise.when (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:1122:31)
    at Promise.promise.promiseDispatch (C:\Users\username\AppData\Roaming\npm\node_modules\bower\lib\node_modules\q\q.js:788:41)
System info:
Bower version: 1.7.9
Node version: 6.3.1
OS: Windows_NT 10.0.10586 x64
```

I'm using version `0.4.0` of `bower-npm-resolver`.

This is caused when the process is `chdir()`-ed synchronously during the `downloadTarball` function (in `npm-utils.js`).  If a second thread also calls `process.chdir()` before the first has finished running the asynchronous `execPackCommand` function, the tarball ends up in the wrong directory.

### PR DESCRIPTION
**Pull request by nfriend**
By using a single directory for downloading (bower's cache directory), the issue described in #10 is avoided.  All packages now downloaded to: `[bower cache directory]/npm-resolver/compressed/` and are extracted into `[bower cache directory]/npm-resolver/uncompressed/[module name]/[module version]`.

Previously, `bower-npm-resolver` was quite diligent about cleaning up the temporary directories it creates.  Most of this cleanup process was removed for the sake of simplicity.  However, a call to `bower cache clean` will delete all temporary files and directories created by this module, which should be intuitive to end users.

Additionally, note that the module `chdir()`s to the `compressed` directory, but never `chdir()`s back out to the original directory.  This was the root cause of the problem described in #10.  This doesn't seem have any noticeable consequences.

On Windows, the default bower cache directory is `%LOCALAPPDATA%\bower\cache`.

### CODE REVIEW

File: src/npm-utils.js [hunk 1]
```diff
@@ -131,14 +130,10 @@ module.exports = {
    * @return {Promise} The promise object.
    */
   downloadTarball: function(pkg, version, dir) {
-    var oldCWD = process.cwd();
     process.chdir(dir);
     return execPackCommand([pkg + '@' + version])
       .then(function(filename) {
         return path.resolve(dir || process.cwd(), filename[0]);
-      })
-      .finally(function() {
```
Comment (mjeanroy) [inline src/npm-utils.js]: Why did you remove this? To avoid side effect, I think it's cleaner to reset the current working directory to its original value, are you ok with that?

**Comment by mjeanroy** [comment]
Awesome, thank you very much @nfriend! Just a simple question in your PR, everything else seems looks good to me!

File: src/npm-utils.js (hunk 1 above)
Comment (mjeanroy) [inline src/npm-utils.js]: Ok, I read your comment in the issue you reported, I understand why you did that.

**Comment by nfriend** [comment]
@mjeanroy No problem!  Did you still have questions about the pull request?  Just making sure you're not waiting for a response from me before merging in the PR.

**Comment by mjeanroy** [comment]
@nfriend No worries, I am just thinking / testing for potential side effects but I plan to release a patched version this week end.

**Comment by mjeanroy** [comment]
@nfriend I dit not see any issue with your fix, so I think it should be ok. If someone reports a problem, we will find an other solution, thank you!

**Comment by mjeanroy** [comment]
@nfriend @qlonik Version 0.5.0 should be available on npm.

**Comment by qlonik** [comment]
Awesome, thanks @mjeanroy!
